### PR TITLE
Tools-2874 Add Aerospike Database server 7.1 support

### PR DESCRIPTION
**Pull request by dwelch-spike**
Adds support for the following configs in server 7.1.

| Name | Action | Section | Human Readable | Default | Data Type | Range Restriction | Required | dynamic |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| max-record-size | default changed from 0 to 64K | namespace | yes, size | 64K |  |  |  |  |
| write-block-size | removed | storage-engine device |  |  |  |  |  |  |
| post-write-queue | removed | storage-engine device |  |  |  |  |  |  |
| tls-refresh-period | New | service | yes, time | 60 seconds | uint32 |  | no | yes  |
| auto-revive | new | namespace (SC only) |  | false | bool |  | no | no |
| batch-max-requests | new | service | no | 0 | uint32 |  | no | yes |
| default-read-touch-ttl-pct | new | namespace | no | 0 | uint32 | 0 to 100 | no | yes |
| flush-size | new | storage-engine device/memory | yes, size | 1M | uint32 | must be a power of 2 and between 4096 and 8388608 bytes | no | yes |
| post-write-cache | new | storage-engine device | yes, size | 256M | uint64 |  | no | yes |
| default-read-touch-ttl-pct | new | set | no | 0 | uint32 | -1 to 100 | no | yes |
| default-password-file | new | security | no |  | string |  | no | no |

### CODE REVIEW

**Review by jdogmcsteezy — COMMENTED** [review]
For my own understanding, are changes in the mgmt-lib and the schemas repo required to support 7.1? If you know, what was needed in the mgmt-lib?

**Comment by dwelch-spike** [comment]
> For my own understanding, are changes in the mgmt-lib and the schemas repo required to support 7.1? If you know, what was needed in the mgmt-lib?

@jdogmcsteezy yes, there are required changes in the schema and the mgmt lib, here are links to both. https://github.com/aerospike/schemas/tree/server7.1 and https://github.com/aerospike/aerospike-management-lib/pull/50 .

The schema changes are what you'd expect, adding the new configs, removing removed ones, and changing some defaults. Most of the changes are reflected by https://aerospike.atlassian.net/wiki/spaces/DEV/pages/3350134792/7.1+Config+and+Metrics+Changes .

The management lib changes are needed because some tables that classify configs are used during config file parsing and writing. In particular, there is a table of config items that are strings that needs to be updated in order to prevent those fields being parsed as integers if they contain integer values. There are a few other tables that need to be checked for updates aswell, most of them are in the asconfig/utils.go file.

**Review by jdogmcsteezy — APPROVED** [review]
LGTM, assuming we are ok with a branch of schemas

**Comment by dwelch-spike** [comment]
We should move to the generated schema as soon as possible but lets use the branch for now.

**Pull request merged**
