### PR TITLE
Tools 2673 don't print usage information when config validation fails

### PR DESCRIPTION
**Pull request by dwelch-spike**

### CODE REVIEW

**Review by jdogmcsteezy — CHANGES_REQUESTED** [review]
I don't think we need to print the usage information if we can't unmarshal the input file, if we can't open the output file, or if we can't write to the output file. Personally, if they provided syntactically correct input I don't think usage information should be displayed. It is interesting that we need to explicitly specify `cmd.SilenceUsage=true`. I don't remember needing to do that for the uda. Most of this logic seemed to be handled automatically.

If you think otherwise we can just merge it

**Comment by dwelch-spike** [comment]
> I don't think we need to print the usage information if we can't unmarshal the input file, if we can't open the output file, or if we can't write to the output file. Personally, if they provided syntactically correct input I don't think usage information should be displayed. It is interesting that we need to explicitly specify `cmd.SilenceUsage=true`. I don't remember needing to do that for the uda. Most of this logic seemed to be handled automatically.
> 
> If you think otherwise we can just merge it

I think the `SilentUsage` call is required because I'm using the `RunE` instead of the `Run` command method. I'll look into some cleaner ways of doing this. I might disable usage output in the root command and then enable it in input checks.

**Review by jdogmcsteezy — APPROVED** [review]

**Comment by dwelch-spike** [comment]
The latest commit Unifies error displaying behavior by.
- Flag parsing errors and invalid commands always print usage. Nothing else does.
- SilenceErrors is set to true in the root command because errors are displayed by the logger in the `Execute` function.
- SilenceUsage is set to true in the root command and instead called by `SetFlagErrorFunc`.
- Mostly removed the multiErrors for simplicity's sake.
- Removed error logs from the convert command because the returned errors are logged in `Execute`

**Review by jdogmcsteezy — APPROVED** [review]
LGTM=

**Pull request merged**
